import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import Transition from "./components/transition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BiteSaver",
  description: "Generated by create next app",
};

type NavItem = {
  title: string;
  path: string;
}[];

export default async function RootLayout({
  children,
  tabs,
  isPriv
}: Readonly<{
  children: React.ReactNode;
  tabs: NavItem,
  isPriv: Boolean
}>) {
  
  // const headersList = await headers();
  // const tabsHeader = headersList.get("X-Tabs");
  // const tabs = tabsHeader ? JSON.parse(tabsHeader as string) : [];
  
  // const cookiesList = await cookies();
  // const authToken = cookiesList.get("authToken");
  // const isPriv = authToken? true:false;

  return (
    <html lang="en" data-theme="night"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-theme="night"
      >
        <div className="min-h-screen">
        <NavBar tabs={tabs} isPriv={isPriv}/>
        <Transition>
          <div className="bg-base-100">
            {children}
          </div>
        </Transition>
        </div>
        <Footer />
      </body>
    </html>
  );
}
